function login() {
    document.getElementById("message").innerHTML =
        "Student logged successfully";
}

function submitAssignment() {
    document.getElementById("message").innerHTML =
        "Assignment Submitted";
}

function logout() {
    document.getElementById("message").innerHTML =
        "Student logged out";
}

function exitApp() {
    document.getElementById("message").innerHTML =
        "Exiting application...";
}